### ISSUE TITLE
Feed!?!

### ISSUE THREAD

**Issue by bkleinen** [heartsofcode/heartofcode#1]
Great site, made me chuckle a lot :) - I missed a feed, happy to provide it - rss.xml doesn't seem to be working? - (is rake preview the way to test it?)

**Comment by catcosmo** [comment]
Thanks for the hint.
There technically is a a feed, which is also filled, see:
view-source:http://heartofcode.org/rss.xml
view-source:http://heartofcode.org/atom.xml
but has a silly validating error 
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fheartofcode.org%2Fatom.xml

can be fixed i think by escaping the author 
{{ site.autor | xml_escape }} or deleting the &-sign (which would have probably been faster than writing this post :) )

feel free to fix, otherwise we'll take care of it asap. 

cheers!

**Comment by drblinken** [comment]
Fixed it. But oops, in the master branch, where the 404 led me to, you seem to be using the gh-pages branch now.

**Comment by heartsofcode** [comment]
thanks a lot!

we merged it into gh-pages and changed the 404, all good.

have a great weekend1
